USE [ibaluk_test]
GO

/****** Object:  Table [dbo].[blob_context]    Script Date: 03/29/2012 16:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[blob_context](
	[id] [varchar](256) NOT NULL,
	[version] [bigint] NOT NULL,
	[blob] [image] NULL,
 CONSTRAINT [PK_blob_context] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO